### PR TITLE
Crag updates and tripwire

### PR DESCRIPTION
**Pull request by Zeno410**

### CODE REVIEW

**Comment by Zeno410** [comment]
Deleting the branch is not possible because that will erase my entire history with RTG. I download this to resolve conflicts and there are none to resolve. This branch is currently a copy of dev, or should be - I copied the dev src directory into my repository

**Comment by whichonespink44** [comment]
When you say 'history', do you mean commit history? Cuz that won't get lost if you delete your fork and re-clone the repo.

**Comment by Zeno410** [comment]
"This action CANNOT be undone. This will permanently delete the Zeno410/Realistic-Terrain-Generation repository, wiki, issues, and comments, and remove all collaborator associations.

Please type in the name of the repository to confirm."

**Comment by whichonespink44** [comment]
Yep, go for it - sounds scarier than it is. All you'll be doing is deleting your local fork. All of your commits are in the remote repo, so they won't get lost. When you re-clone, it'll pull down the entire commit history from the beginning of the project, including all of your commits and everyone else's, and you'll have a fresh copy of the repo (and hopefully no more conflicts).

**Pull request closed without merging**
