### PR TITLE
Volcanoes changes/fixes

### LINKED ISSUE #275: Volcanoes getting cut-off during chunk generation
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-17?comment=498

### PR DESCRIPTION
**Pull request by VelocityRa**
#275 Is solved here, but I may push other changes to Volcanoes in the following days.
Sorry about the Merge commit, I'll try rebasing next time so as not to litter our commit history with fork merges.

### CODE REVIEW

**Comment by Ezoteric** [comment]
need to see some proof of this :P

**Comment by VelocityRa** [comment]
Here's a shitty slideshow: http://slideful.com/v20160508_0618189237085224_pf.htm

**Comment by whichonespink44** [comment]
I knew volcanoes would bring @Ezoteric out of hiding :volcano: :wink:

**Comment by Ezoteric** [comment]
well im not convinced yet i did download the dev of yours and ill try test it myself :P 
I need to see it at a normal spawnrate on multiple biomes spread :P

I was still reading all the shit pinky :P

**Comment by whichonespink44** [comment]
Latest volcano stuff isn't in dev yet, but should be soon.

**Comment by VelocityRa** [comment]
Lots of changes in the latest commit, gonna need some testing.

**Comment by VelocityRa** [comment]
Noo I wanted to push the Jungle vine fix here :P

**Comment by whichonespink44** [comment]
Doh! Sorry... hope it's not gonna mess your stuff up? Can you push to dev instead?

**Comment by Ezoteric** [comment]
BTW, something sort of related.

So for my mushroom island convertion to tropical, i just reset the purple blocks to dirt etc ?

**Pull request merged**
