### PR TITLE
Draft Terrain draft

### PR DESCRIPTION
**Pull request by Zeno410**
Basically good to release for comment. Noise problem not properly fixed but hacked to not be noticeably problematic. River/lake system retuned based on fixed noise. A few biomes fixed. Still haven't reviewed HL WindyIsland and Lowlands; BoP Glacier, Quagmire, and Savannah; or thoroughly surveyed vanilla M biomes.

### CODE REVIEW

**Comment by whichonespink44** [comment]
Cool, I'm going to take it for a test drive shortly.

I'll probably release the first 0.8.0 snapshot tomorrow night if that's cool?

**Comment by Zeno410** [comment]
Yes, I think this should go out as a snapshot relatively soon, with a real push for comments ("Speak now or forever hold your peace!") I think 0.9.0 should go out with soft lockdowns on the basic terrain system, river and lakes, and the vanilla/BoP/Highlands/TC biomes, making this the last version for anybody to say things on those. I'm thinking maybe we should ask for comments on the "minor biomes" (Growthcraft, etc.) as I'm not familiar with them and so *they* go into soft lockdown in 0.9.0 as well if we don't get comments. EB and EBXL have to be worked on - I'd be shooting for their draft versions in 0.9.0

**Comment by srs-bsns** [comment]
Awesome. I just updated my fork and am about to make a test build which I'll look at later.
For 0.9.0 I'm going to look into creating GUI Configs. Since RTG doesn't add blocks, config settings should be able to be modified after the game is loaded without having to restart minecraft. That could be a huge convenience in many cases.

**Comment by Zeno410** [comment]
One thing missing from this is Topi's changes to Mesa and Savanna.

**Comment by topisani** [comment]
Yep its surface and terrain for all mesa and Savanna plateau variations, + canyoncolour. Take it from the 1.8 repo

**Comment by whichonespink44** [comment]
I've ported that stuff locally - just testing it now.

**Pull request merged**
