### PR TITLE
1.8.9 update

### PR DESCRIPTION
**Pull request by topisani**
I saw there were no plans to update to 1.8, so I did it myself. It does not yet work completely, but should be done during the next week or so. However i am opening this PR now, hoping someone will help test it, as there are many weird bugs that could show up.

### CODE REVIEW

**Comment by topisani** [comment]
yeh sorry about that, im kinda new to the whole github PR thing. The main thing is that, to get and maintain a usable version, it would help if someone used it, and i thought this was the best way to get in touch with both you and the users. Would it be possible to, as this gets in a more usable state (I only need to figure out 1 more thing untill it should work), to get this version mentioned on the forum? I would also like to keep merging in your updates. Whatever you guys think is appropriate, I am glad to be of help!

**Comment by whichonespink44** [comment]
Thanks for this contribution @topisani 

As Zeno mentioned, we can't merge this into `master`, but... I'll create a new branch later today that you can re-submit the PR to. When you do, we'll discuss internally what the next course of action will be.

To be totally transparent, there's a very good chance that we won't end up releasing the 1.8 version until RTG v1.0 is released, but there might be something we can do in the meantime.

But first things first, let's get your stuff onto a separate branch... I'll post the details here when the branch is ready.

**Comment by topisani** [comment]
Sounds great
I will keep refining, for now it generates but I am still missing caves, ravines, granite/andesite/diorite, ocean monuments, and I made a few mistakes when updating the code for some of the trees. I am also going to add compatibility with at least some other mods, for now only BOP and thaumcraft _should_ work. I intend to keep merging your updates, and I also may have some contributions to the 1.7 version coming up.

**Comment by whichonespink44** [comment]
Ok, I've created a `1.8.9` branch from `dev`:

https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.8.9

If you could update your fork and re-submit the PR targeting that branch, we'll get it merged.

Also, if it's cool with you, I'd like to send you an invite to join the Team RTG organization on GitHub which will give you access to our Gitter room and make communicating a lot easier moving forward. We've already had a bit of an internal discussion about things, but it would be good to get you involved in the discussions if that's cool?

No worries if not.

**Comment by topisani** [comment]
Sure thing, sounds great!

**Pull request closed without merging**
