### PR TITLE
Working CC/vanilla merger

### PR DESCRIPTION
**Pull request by Zeno410**
Working version using RTG with non-RTG biome layouts. Still has the surface blotches.

### CODE REVIEW

**Comment by Ezoteric** [comment]
what do you mean by blotches ? can you show that with a screenshot ?

**Comment by Zeno410** [comment]
zeno410@aol.com




-----Original Message-----

**Comment by Zeno410** [comment]
Ezoteric, I sent a pic. Sorry for the delay.

**Comment by Ezoteric** [comment]
where the picture at :P

**Pull request merged**
