### PR TITLE
Compatibility with biome limit extending mods.

### PR DESCRIPTION
**Pull request by elix-x**
Biome id limit of 256 can be extended using a lot of asm. But it is possible.
Mods such AIC 2.0 and NEID have done it, so to support them you just have to make your biome array have length of vanilla's.

### CODE REVIEW

**Comment by Zeno410** [comment]
This looks straightforward, but there's more code than this that will need to change. The biome repair code will also need fixing, and probably some other things as well. But we should still take the pull.

**Comment by whichonespink44** [comment]
Thanks for that @elix-x :+1:

**Comment by Zeno410** [comment]
I searched the code base for "256", many of which references are to the biome array and need a similar change:

Found 4,914 match(es) in 352 file(s)

Um, yes, a bit more work! The vast majority are references to the 256 height but somebody's gotta look at a lot of code.

**Comment by whichonespink44** [comment]
I can do the refactoring. @Zeno410 does it need to be done before we release snapshot 5? either way, I'll create a new issue for this.

**Comment by elix-x** [comment]
Awesome!
Now i just have to report the same thing to BoP, highlands, extra biomes...

**Pull request merged**
