### PR TITLE
Update ConfigBOP.java

### PR DESCRIPTION
**Pull request by Ezoteric**
Now its correct ;)

### CODE REVIEW

**Comment by whichonespink44** [comment]
Sneaky little asterisks!! :snake:

**Comment by Ezoteric** [comment]
Haha BTW I'm checking this latest build of yours and see what's gonna happen haha

**Comment by whichonespink44** [comment]
Hopefully the same thing that happen with 0.0.6!!!  :wink:

**Comment by Ezoteric** [comment]
well, i still get a standard vanilla biome, and also i hardly get any ocean...

The only ocean i have is in the top right corner and all maps are like this. only 1 ocean and rivers between biomes are mostly treeless :P

rtgtest

**Comment by whichonespink44** [comment]
I wonder if it has something to do with the temp/rain values we're using in BiomeBase.java? Those were the setting from RWG, which might've been perfect for the old base biomes, but maybe we need to play around with some different values for those? Or maybe add some additional climates... like maybe:

Very Hot
Hot
Warm
Normal
Cool
Cold
Very Cold

Just thinking maybe that will be enough to smooth out the transitions a bit? I wish I had a super computer so I could load a new world & generate a map in less than a minute!!!  :sob:

**Comment by Ezoteric** [comment]
lol in less then a minute haha keep dreaming :P

And yes, that was what i said before the more the better transition, but it seems RWGs transition code isnt really working or does it ?

I mean in chunkmanager file you have the hot cold wet shit but i think thats not working like it should.

**Comment by Ezoteric** [comment]
Here i created a gist:

https://gist.github.com/Ezoteric/b05fa6529f4afcfd4151

See if you like it ;)

**Comment by Ezoteric** [comment]
btw you deleted the volcano map :p

**Comment by Ezoteric** [comment]
Hmmz, i think i found something important. 
I think rtg/rwg skips genlayer from MC therefor were not getting islands for 1 thing to name.

I was looking into some files and EB BOP etc all use genlayer.
Now if you look at GenLayerBiome.java from MC and biomemanger from forge youll see we need to stop using RWGs way and update the layer files with our own stuff.

I think THAT is the way to get what we want, cause MC self allready has code to make sure desert aint bordering ice biomes etc

**Comment by whichonespink44** [comment]
_"I think THAT is the way to get what we want, cause MC self allready has code to make sure desert aint bordering ice biomes etc"_

It's worth a shot... if we could still generate breathtaking, realistic terrain whilst doing pretty much everything else the way vanilla MC does it, that would be perfect. After I'm done refactoring the two 'Chunk' files in the `truffle-shuffle` branch, that's the last of the rewrite that I'm doing, so we'll be able to start working on the GenLayer stuff. You still up for that screenshare session to get GD up and running on your system?

**Comment by whichonespink44** [comment]
_"btw you deleted the volcano map :p"_

It will be back :wink:

**Comment by Ezoteric** [comment]
Yes I'm still up for that even though I never used hangouts :p

**Comment by Ezoteric** [comment]
Btw at what time you want to do that

**Comment by whichonespink44** [comment]
I can do anytime from now until 10pm GMT... instead of Hangouts then, let's do a Join.Me meeting... you'll need to download and install the client, but after that's it's pretty straightforward. Just let me know what time's best for you and I'll PM you link via Minecraft Forums.

**Comment by Ezoteric** [comment]
now is fine by me pm me your name on MCF

**Pull request merged**
