### PR TITLE
Improved vanilla biome aesthetics.

### PR DESCRIPTION
**Pull request by whichonespink44**

### CODE REVIEW

**Comment by Ezoteric** [comment]
BTW you forgot to add extremehillsedge :P

**Comment by whichonespink44** [comment]
[Extreme Hills Edge and Frozen Ocean](http://minecraft.gamepedia.com/Biome#Unused_biomes) aren't enabled in vanilla MC. :wink:

**Comment by Ezoteric** [comment]
Eb has then enabled!!! *stompfoot* 😛

**Comment by whichonespink44** [comment]
EB has a biome _called_ Extreme Hills Edge... that doesn't mean it's the same biome. :stuck_out_tongue:

**Comment by Ezoteric** [comment]
oow shit yeah he could made them itself yes

**Pull request merged**
