### PR TITLE
Climate change

### PR DESCRIPTION
**Pull request by whichonespink44**

### CODE REVIEW

**Comment by Ezoteric** [comment]
Hey m8 did you already tested this ? :)

**Comment by whichonespink44** [comment]
I've tested it, but it's probably not what you're thinking... hot-2-cold still isn't working yet, but I wanted to push the branch as it had some changes I wanted in `master`

**Comment by Ezoteric** [comment]
Alrighty then :p I saw you changed a lot haha so couldn't see it all :p

**Comment by Ezoteric** [comment]
Is there a way to make lakes more rare ? :)

**Pull request merged**
