### PR TITLE
Fix village bug + improve desert villages

### PR DESCRIPTION
**Pull request by VelocityRa**
Solves #607.

### CODE REVIEW

**Comment by topisani** [comment]
great work! remember to add the PR-REVIEW label ;)

**Comment by VelocityRa** [comment]
Thanks, got it!

**Comment by whichonespink44** [comment]
Looks good - does this mean we don't need that 'chunkZ + 16' that we discussed yesterday?

**Comment by VelocityRa** [comment]
Yup, we don't.

**Comment by whichonespink44** [comment]
Nice one.

I'll merge this into dev tonight before we release snapshot 3.

**Comment by Zeno410** [comment]
Nice work!

**Pull request merged**
