### PR TITLE
New ore gen system + re-decorated vanilla forest biomes.

### PR DESCRIPTION
**Pull request by whichonespink44**

### CODE REVIEW

**Comment by Ezoteric** [comment]
Add the snow layer also plz :)

**Comment by whichonespink44** [comment]
Pull request plz ;)

**Comment by Ezoteric** [comment]
It's a few letters you have to add haha lazy ass ;)

**Comment by whichonespink44** [comment]
Just want you to get the credit for the change. Team RTG FTW!!! :smile:

**Comment by Ezoteric** [comment]
Or if some ppl complain you tell em to blame me ;)  haha

**Comment by whichonespink44** [comment]
haha, you know me so well :wink:

**Pull request merged**
