### PR TITLE
Organic Biome System (formerly known as Faked Biome System)

### PR DESCRIPTION
**Pull request by whichonespink44**
So this is the ported 'faked biome' system from the `RTG2` rewrite.

As far as I can tell, it's mostly working, but there are definitely some issues that need to be resolved:

- [ ] Some biome transitions produce 'checkerboard' terrain 🏁 
- [ ] Oceanic biomes not being filled with water 🌊 

Those are the only issues I spotted - there may be more. But it was working fine for a lot of the biomes that I tested.

Speaking of which, the way I tested the organic biomes was by commenting out the `RealisticBiome{MOD}Base.addBiomes();` line in RTG.java and running the game with that mod installed locally.

Anyway, I don't foresee this being merged into `dev` anytime soon. To do so would require some assistance from @topisani who's quite busy with school and other projects at the moment.

### CODE REVIEW

**Comment by topisani** [comment]
after christmas ill have some time to help look at this. Remind me around then, cause ill probably forget.

**Comment by srs-bsns** [comment]
The 'checkerboard' terrain is likely a noise floor issue. Possible means of a fix can be found here: 19fd9d6ddfdda4d5692a8478e032811a1887c161

**Comment by topisani** [comment]
[Noise Floor](https://www.wikiwand.com/en/Noise_Floor_(Rarities:_1998%E2%80%932005))

**Comment by whichonespink44** [comment]
Closing this for now... will re-submit a PR based on the 1.11.2 version of this branch.

**Pull request closed without merging**
