### PR TITLE
i think this is how ?

### PR DESCRIPTION
**Pull request by Ezoteric**
i think this is how ?

### CODE REVIEW

**Comment by Ezoteric** [comment]
Only those with write access to this repository can merge pull requests.

MERGE BOSS :P

**Comment by whichonespink44** [comment]
Boss, haha :stuck_out_tongue:  Ok, I'm looking at it now. It says there's conflicts, but I'll see if I can figure it out.

**Comment by whichonespink44** [comment]
Not gonna be able to merge this one I'm afraid, but no worries, let's do our screenshare tomorrow night and we'll get the branch setup properly in your dev environment. That cool?

From looking at the diff files, there's definitely some interesting stuff going on in there. Did you say that some stuff was generating?

**Comment by Ezoteric** [comment]
Yeah I did had a normal desert as in old vanilla style terrain next to my desert haha weird.

Also I have no conflicts

**Comment by whichonespink44** [comment]
_"Also I have no conflicts"_

No, it means that if I were to try and merge this pull request into the branch, it wouldn't be able to because there are 'conflicts' in the code and it doesn't know how to merge them. From what I could see, it looks like you're trying to add back in some really old code along with your new stuff. Looks like maybe you weren't syncing with the latest master very often? In any case, it's all good because tomorrow we'll get you setup with GitHub Desktop and this whole pull request stuff will be a piece of :cake:

**Comment by Ezoteric** [comment]
weird i downloaded your newest zip....

**Comment by Ezoteric** [comment]
ah well its gonna be ok :p

**Comment by whichonespink44** [comment]
I'm gonna close this pull request, but I'll try to manually add your stuff onto the branch and see if I can get it working.

**Comment by Ezoteric** [comment]
Here is a picture with rivers off, now you dont have the river biome just the rivers it self.

Red circle is i what i think are lakes as it has taiga biome as name
Black circle are both called desert and desert hills is also called desert hills, so i think with gen layer its also calling up vanilla biomes :P

http://i.imgur.com/QIk55Pn.jpg

**Comment by whichonespink44** [comment]
Cool, I'll take a look... so, are you saying that you disable the River biome, but rivers still generate? When you fly over the 'river' does the biome name say 'River' ?

**Comment by Ezoteric** [comment]
i think it does yes, let me start mc

**Comment by Ezoteric** [comment]
Yes it does say river. but that would be logic as you hardcode them with the biomes, its just not making a biome called river which i think is BS anyway, and the biome river also makes ugly large flat land from sand or gras :P

**Comment by whichonespink44** [comment]
If that's what it does, I'll prevent the River biome from generating as a separate biome then. They look ugly when they generate that way anyway :stuck_out_tongue_winking_eye:

**Comment by Ezoteric** [comment]
yeah were on the same page on that one ;)

**Comment by whichonespink44** [comment]
:+1:

**Comment by Ezoteric** [comment]
also if we get layers working we can use the shorelayer to make our sick shores :D

**Comment by Ezoteric** [comment]
but ill wait patiently for your awesomeness rewrite ;)

I think with this you can go a long way ;)

**Comment by whichonespink44** [comment]
Once we get you setup with GD, you won't need to wait :wink:

**Comment by Ezoteric** [comment]
lol are you saying your done with the rewrite ? i dont believe that ;)

**Comment by whichonespink44** [comment]
Ha! I wish... no, I just meant that you can work on the Gen Layer stuff whilst I work on the rewrite... as long as you keep updating your branch regularly, you'll always the latest version... and no conflicts when it comes time to merge your stuff back in. Plus, I'll be able to flip back and forth between my rewrite branch and your Gen Layer branch... jesus, I really need to quit my day job... all I wanna do is CODE!!!!!

**Comment by Ezoteric** [comment]
aha thats nice yes, tomorro we could do that yes :)

btw i added all the shit peice by piece now see if its good now

**Comment by Ezoteric** [comment]
isnt your job coding ? haha

**Comment by whichonespink44** [comment]
Grrr, now that I've already added it manually... NOW you do proper pull requests :stuck_out_tongue_closed_eyes:  haha, it's all good... I'm merge those now and give it a test run and then you can explain to me what the hell's going on with those layers haha :)

**Comment by whichonespink44** [comment]
and yes, my day job is coding, but it's not Minecraft coding :)

**Comment by Ezoteric** [comment]
looooooooooooooooooooooool

yeah well if you would work MC it would be better :P 
I should be a program leader cause of my super cool ideas ;)
Im more like a leader then a worker haha :P

BTW can you upload me a compiled version of your master without rwg ? 
so i can compair the results ?

**Comment by Ezoteric** [comment]
My other eclipse doesnt work lol and my new eclipse i wont fuck with anymore :P

**Comment by whichonespink44** [comment]
You mean a JAR of the latest `gen-layers` branch?

**Comment by Ezoteric** [comment]
no a jar of your master where you delted all the stuff and not added my stuff from the gen layers

**Comment by whichonespink44** [comment]
oh... yep, sure thing... gimme a couple minutes... friggin Mesa biomes! they're everywhere!! think i might look into that biome weighting stuff next

**Comment by Ezoteric** [comment]
btw the special biome thing i also added cause i think that also means it doesnt spawn much and thats exactly what the volcano needs to be.

What we also could do is spawn the volcano on a few biomes. But it needs to be a better one then the current one :P

**Comment by Ezoteric** [comment]
Yeah, this map gen isnt working cause of one major thing, special biome genlayer creates the subbiomes like mesa platue en xhills M etc 
these are no generated with the same weight cause you made those subbiomes normal biomes :P

**Comment by Ezoteric** [comment]
btw i see i have to add some more genlayer files with it cause there are a few more files using vanilla stuff. 

Ill make those also now.

**Comment by whichonespink44** [comment]
Here's the latest version with the RWG stuff removed: https://drive.google.com/file/d/0B7tFzVqlzYLPMEdycS1KdDQ1X3M/view?usp=sharing

**Comment by Ezoteric** [comment]
k generating a map now and ill see what happens.

Also im done adding the other genlayer files i saw i needed so ill test that also and then im calling it a day haha :P 

I think i added almost all stuff bop did so i guess its a start :P

**Comment by Ezoteric** [comment]
yeah, now i dont have vanilla biomes, so yes my genlayer code does work but it needs tweaking to make sure it doesnt use vanilla crap biomes :P

**Comment by Ezoteric** [comment]
correct that i still have weird desert...

**Comment by Ezoteric** [comment]
ok got crash now so its bedtime for me :P 

talk to you tomorro :p

**Comment by Ezoteric** [comment]
ava.lang.ClassCastException: net.minecraft.world.gen.layer.GenLayerZoom cannot be cast to rtg.world.gen.layers.GenLayerRTG
	at rtg.world.gen.layers.GenLayerRTG.initializeAllBiomeGenerators(GenLayerRTG.java:78)
	at rtg.world.ChunkManagerRealistic.<init>(ChunkManagerRealistic.java:71)
	at rtg.world.WorldTypeRealistic.getChunkManager(WorldTypeRealistic.java:18)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:61)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
	at net.minecraft.world.World.<init>(World.java:244)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Pull request closed without merging**
