### PR TITLE
Fix for surface ponds

### PR DESCRIPTION
**Pull request by Zeno410**
WorldGenLakes replaced with WorldGenPonds. Ponds are now flush with at
least some land, are now unlikely to leave stuff floating in midair,
and don't intrude into house.

### CODE REVIEW

**Comment by whichonespink44** [comment]
1233400426_guy falls of chair

**Comment by whichonespink44** [comment]
I don't think I've ever been more excited to test a PR!! :dancer: 

Does this also fix BOP ponds as well?

**Comment by Zeno410** [comment]
Yes, it does. Bayou, Wetlands, Marsh, etc. - all much better.

**Comment by topisani** [comment]
Y no screenies?

**Comment by Zeno410** [comment]
Lazy. Also, you could get decent ponds from the old system, just not very often, so a screenie doesn't prove much. However, it doesn't seem to be working right in Bayou after all - I'm still getting cutoff trees. It's still a big improvement and I'll take a look at the cutoff trees when I get a chance.

**Comment by whichonespink44** [comment]
Yeah, I've noticed the occasional floating tree or floating piece of tallgrass from where the pond digs into the surface, but... on the whole, it's definitely a massive improvement.

If you think you can improve it even further, go for it... but... even if it doesn't get any better than it is right now, I'd still be happy. I may even enable ponds on my survival worlds now :)

**Pull request merged**
