### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Ezoteric**
I think this is a good start and makes more sense.
When the biome is small enough it even looks like a valley :)

### CODE REVIEW

**Comment by whichonespink44** [comment]
Cool, can't wait to check it out!! :smile: 

Can you do me a favour though? Instead of replacing `TerrainVanillaSavannaPlateau` with `TerrainCanyon` and `SurfaceVanillaSavannaPlateau` with `SurfaceGrassCanyon` ... can you replace the **contents** of _TerrainVanillaSavannaPlateau.java_ with the **contents** of _TerrainCanyon.java_ ? And the same for the surface as well?

Technically, it still works the way you have it, but... I want each biome to have its own terrain and surface file (architectural reasons).

(I can do it myself if you don't have time, just let me know.)

**Comment by Ezoteric** [comment]
yes i can, the reason is didnt is, you may want to check it out yourself first before i start messing with the other files ;)

**Comment by Ezoteric** [comment]
OK changed the other files so you can delete this one :)

**Comment by whichonespink44** [comment]
Cool, thanks man. Can't wait to see it... maybe you can post a screenshot? In the meantime, I'm quitting my job so I can before a full-time Minecraft modder!!!! :stuck_out_tongue_winking_eye:

**Comment by Ezoteric** [comment]
Lol I hope that's a fucking joke right?

Btw i was looking at colored lights mod and that dude said he had access to a better decompiled mc :o maybe you should ask as well haha

**Comment by whichonespink44** [comment]
Sadly, yes, it's a joke... but at least I'll be getting 3 weeks off for the holidays soon... lots of time for RTG then!! :smile:

**Comment by Ezoteric** [comment]
lawl :) you a addict :) but you dont hear me complain haha 
this mod becomes more complete by the week thnx to you :)

**Comment by whichonespink44** [comment]
I've created a new branch called [`vanilla-savanna-plateau`](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/vanilla-savanna-plateau) that has your stuff in, so I'll close this pull request, but feel free to keep working on it if you want, or I could finish it off if you just tell me what you had in mind?

**Comment by whichonespink44** [comment]
Actually, this is probably a better link: https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/9ee09e54f72f475d4eff7bb9d28daf52fa248cf8

**Comment by whichonespink44** [comment]
In fact, check out the latest version of the [`vanilla-savanna-plateau`](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/vanilla-savanna-plateau) branch and let me know what you think. Made a few tweaks ;)

**Pull request closed without merging**
