### PR TITLE
Updating to dev branch

### PR DESCRIPTION
**Pull request by Zeno410**

### CODE REVIEW

**Comment by whichonespink44** [comment]
Closing as per Discord discussion.

**Comment by Zeno410** [comment]
Seems we should have merged it because guess what happened with my latest one-line change?

**Comment by whichonespink44** [comment]
I'm wondering if maybe a full re-clone of the repository would help. Something seems to have gotten glitched somewhere along the way, so maybe deleting your local fork entirely and re-cloning the repo will give it a fresh start.

**Comment by Zeno410** [comment]
No, my fork was fine a couple hours ago. I think the conflict is with Velo's changes. Wasn't he working on an older version?

**Comment by whichonespink44** [comment]
Hmm, I don't think so - his last commit to dev was [5 days ago](https://github.com/Team-RTG/Realistic-Terrain-Generation/commits/dev).

I'm not sure I'd call the fork 'fine' at the moment since it can't submit a PR without conflicts. Still think a full re-clone is the way to go. If nothing else, then at least we can rule it out of the equation as to what's causing the issue. ¯\\\_(ツ)_/¯

**Pull request closed without merging**
