### PR TITLE
More re-factoring and experimental tweaks to biomes

### PR DESCRIPTION
**Pull request by whichonespink44**

### CODE REVIEW

**Comment by Ezoteric** [comment]
Doezelen the mushroomisland work like this?  :p

**Comment by Ezoteric** [comment]
Does... lol

**Comment by whichonespink44** [comment]
Nope, it still generates inland :cry:  ...  but I'm going to try a few other things today before going back to GenLayers.

**Comment by Ezoteric** [comment]
aaawh :P

well i think i gonna try adding all EB stuff to this cause EB is the BOMB !! :P

**Comment by whichonespink44** [comment]
I got really close with EB's gen layer stuff, but after I got it all setup, it kept crashing at the same spot as the BOP stuff did.... I think my next attempt will involve getting just an empty genlayer system in place that doesn't do anything, and then I'll start adding in functionality piece by piece until it breaks.

Before that though, I need to release 0.0.7 since the debug code I wrote isn't working on servers. Should have it released in the next hour.

**Comment by Ezoteric** [comment]
Ow weird. Do you still have that eblayer setup ? Saves me doing the hassle :p haha

Yeah I saw on mcf :)

**Comment by Ezoteric** [comment]
Maybe the problem is that MC has too many ways to get the vanilla biomes orso and we need to make sure it sees our as their ?

**Pull request merged**
